config/routes.rb
Rails.application.routes.draw do
  get '/', to: "sessions#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  resources :users
  resources :ideas
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, User, id: user.id
   if user.admin?
     can :read, :all
   end

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :idea_images
  has_many :images, through: :idea_images
end

app/models/idea_image.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  enum role: %w(default admin)

  has_many :ideas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to login_path, :alert => exception.message
  end


  private
  def current_user
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_filter :authorize, only: [:show]
  def show
    if current_user.ideas.all.count == 1
      @ideas = Array.new(1,current_user.ideas.all)
    else
      @ideas = current_user.ideas.all
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    puts "Idea Id: #{params[:id]}"
    puts "updated title: #{params[:idea][:title]}"
    puts "updated text: #{params[:idea][:text]}"
    Idea.find(params[:id])
        .update_attributes( title: params[:idea][:title],
                            text: params[:idea][:text],
                            category_id: params[:idea][:category_id])
    redirect_to idea_path(current_user)
  end

  def new
    @idea = Idea.new(title: params[:title], text: params[:text], user_id: current_user.id)
  end

  def create
    puts "outputting params"
    puts params.inspect
    puts "new title"
    puts params[:idea][:title]
    puts "new text"
    puts params[:idea][:text]
    puts "user_id"
    puts params[:idea][:user_id]
    Idea.create(title: params[:idea][:title],
                text: params[:idea][:text],
                user_id: params[:idea][:user_id],
                category_id: params[:idea][:category_id])

    redirect_to idea_path(current_user)
  end

  def destroy
    puts "Id of post to be destroyed #{params[:id]}"
    Idea.find(params[:id]).destroy
    redirect_to idea_path(current_user)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in."
      redirect_to idea_path(user)
    else
      flash[:errors] = "Invalid login"
      render :new
    end

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:show]
  def show
    @user = User.find(params[:id])
    flash[:alert] = "Hello Admin" if current_user.admin?
    authorize! :read, @user
  end

  def new
    @user = User.new(name: params[:name],
                     password: params[:password],
                     password_confirmation: params[:password_confirmation],
                     role: params[:role])
  end

  def create
    puts "outputting params"
    puts params.inspect
    puts "user name"
    puts params[:user][:name]
    puts "password"
    puts params[:user][:password]
    puts "password confirmation"
    puts params[:user][:password_confirmation]

    User.create(name: params[:user][:name],
                password: params[:user][:password],
                password_confirmation: params[:user][:password_confirmation],
                role: 0)
    redirect_to login_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>


<%= form_for(@idea) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :text %><br>
  <%= f.text_field :text %><br>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.submit %>

<% end %>

app/views/ideas/new.html.erb
<h1>NEW IDEA TIME</h1>
<%= current_user.name %>

<%= form_for(@idea) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :text %><br>
  <%= f.text_field :text %><br>
  <%= f.hidden_field :user_id %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.submit %>

<% end %>

app/views/ideas/show.html.erb
<% @ideas.each do |idea| %>
  <h2><%= idea.title %></h2>
  <%= idea.text %></br>
  <%= idea.category.name %></br>
  <%= link_to "Edit", edit_idea_path(idea) %><br>
  <%= link_to "Destroy", idea, method: :delete %>
<% end %>

<p><%= link_to "Create New Idea", new_idea_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewIdeaBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/new.html.erb
<h1>LETS CREATE A USER YEAH</h1>
<%= form_for(@user) do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br>

  <%= f.label :password %></br>
  <%= f.password_field :password %></br>

  <%= f.label :password_confirmation %> </br>
  <%= f.password_field :password_confirmation %> </br>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h1>User Show Page</h1>
<div id="banner">
  Welcome, <%= @user.name %>
</div>